static void class_dealloc ( PyClassObject *op );
static PyObject *class_lookup ( PyClassObject *cp , PyObject *name , PyClassObject **pclass );
static PyObject *class_getattr ( PyClassObject *op , PyObject *name );
static void set_slot ( PyObject **slot , PyObject *v );
static void set_attr_slots ( PyClassObject *c );
static char *set_dict ( PyClassObject *c , PyObject *v );
static char *set_bases ( PyClassObject *c , PyObject *v );
static char *set_name ( PyClassObject *c , PyObject *v );
static int class_setattr ( PyClassObject *op , PyObject *name , PyObject *v );
static PyObject *class_repr ( PyClassObject *op );
static PyObject *class_str ( PyClassObject *op );
static void instance_dealloc ( PyInstanceObject *inst );
static PyObject *instance_getattr1 ( PyInstanceObject *inst , PyObject *name );
static PyObject *instance_getattr ( PyInstanceObject *inst , PyObject *name );
static int instance_setattr1 ( PyInstanceObject *inst , PyObject *name , PyObject *v );
static int instance_setattr ( PyInstanceObject *inst , PyObject *name , PyObject *v );
static PyObject *instance_repr ( PyInstanceObject *inst );
static PyObject *instance_compare1 ( PyObject *inst , PyObject *other );
static int instance_compare ( PyObject *inst , PyObject *other );
static long instance_hash ( PyInstanceObject *inst );
static int instance_length ( PyInstanceObject *inst );
static PyObject *instance_subscript ( PyInstanceObject *inst , PyObject *key );
static int instance_ass_subscript ( PyInstanceObject *inst , PyObject *key , PyObject *value );
static PyObject *instance_item ( PyInstanceObject *inst , int i );
static PyObject *instance_slice ( PyInstanceObject *inst , int i , int j );
static int instance_ass_item ( PyInstanceObject *inst , int i , PyObject *item );
static int instance_ass_slice ( PyInstanceObject *inst , int i , int j , PyObject *value );
static PyObject *generic_unary_op ( PyInstanceObject *self , PyObject *methodname );
static int halfbinop ( PyObject *v , PyObject *w , char *opname , PyObject **r_result , PyObject *(*thisfunc )Py_PROTO ((PyObject *,PyObject *)), int swapped );
static int instance_coerce ( PyObject **pv , PyObject **pw );
static PyObject *instancemethod_getattr ( PyMethodObject *im , PyObject *name );
static void instancemethod_dealloc ( PyMethodObject *im );
static int instancemethod_compare ( PyMethodObject *a , PyMethodObject *b );
static PyObject *instancemethod_repr ( PyMethodObject *a );
static long instancemethod_hash ( PyMethodObject *a );
static int instance_nonzero(PyInstanceObject *self);
static PyObject * instance_pow(PyObject *v, PyObject *w, PyObject *z);
