static PyObject *err_ovf ( char *msg );
static PyIntObject *fill_free_list ( void );
static void int_dealloc ( PyIntObject *v );
static int int_print ( PyIntObject *v , FILE *fp , int flags );
static PyObject *int_repr ( PyIntObject *v );
static int int_compare ( PyIntObject *v , PyIntObject *w );
static long int_hash ( PyIntObject *v );
static PyObject *int_add ( PyIntObject *v , PyIntObject *w );
static PyObject *int_sub ( PyIntObject *v , PyIntObject *w );
static PyObject *int_mul ( PyIntObject *v , PyIntObject *w );
static int i_divmod ( PyIntObject *x , PyIntObject *y , long *p_xdivy , long *p_xmody );
static PyObject *int_div ( PyIntObject *x , PyIntObject *y );
static PyObject *int_mod ( PyIntObject *x , PyIntObject *y );
static PyObject *int_divmod ( PyIntObject *x , PyIntObject *y );
static PyObject *int_pow ( PyIntObject *v , PyIntObject *w , PyIntObject *z );
static PyObject *int_neg ( PyIntObject *v );
static PyObject *int_pos ( PyIntObject *v );
static PyObject *int_abs ( PyIntObject *v );
static int int_nonzero ( PyIntObject *v );
static PyObject *int_invert ( PyIntObject *v );
static PyObject *int_lshift ( PyIntObject *v , PyIntObject *w );
static PyObject *int_rshift ( PyIntObject *v , PyIntObject *w );
static PyObject *int_and ( PyIntObject *v , PyIntObject *w );
static PyObject *int_xor ( PyIntObject *v , PyIntObject *w );
static PyObject *int_or ( PyIntObject *v , PyIntObject *w );
static PyObject *int_int ( PyIntObject *v );
static PyObject *int_long ( PyIntObject *v );
static PyObject *int_float ( PyIntObject *v );
static PyObject *int_oct ( PyIntObject *v );
static PyObject *int_hex ( PyIntObject *v );
