static void tupledealloc ( PyTupleObject *op );
static int tupleprint ( PyTupleObject *op , FILE *fp , int flags );
static PyObject *tuplerepr ( PyTupleObject *v );
static int tuplecompare ( PyTupleObject *v , PyTupleObject *w );
static long tuplehash ( PyTupleObject *v );
static int tuplelength ( PyTupleObject *a );
static PyObject *tupleitem ( PyTupleObject *a , int i );
static PyObject *tupleslice ( PyTupleObject *a , int ilow , int ihigh );
static PyObject *tupleconcat ( PyTupleObject *a , PyObject *bb );
static PyObject *tuplerepeat ( PyTupleObject *a , int n );
