static PyObject *_PyBuffer_FromMemory ( PyObject *base , void *ptr , int size , int readonly );
static PyObject *_PyBuffer_FromObject ( PyObject *base , int offset , int size , getreadbufferproc proc , int readonly );
static void buffer_dealloc ( PyBufferObject *self );
static int buffer_compare ( PyBufferObject *self , PyBufferObject *other );
static PyObject *buffer_repr ( PyBufferObject *self );
static long buffer_hash ( PyBufferObject *self );
static PyObject *buffer_str ( PyBufferObject *self );
static int buffer_length ( PyBufferObject *self );
static PyObject *buffer_concat ( PyBufferObject *self , PyObject *other );
static PyObject *buffer_repeat ( PyBufferObject *self , int count );
static PyObject *buffer_item ( PyBufferObject *self , int idx );
static PyObject *buffer_slice ( PyBufferObject *self , int left , int right );
static int buffer_ass_item ( PyBufferObject *self , int idx , PyObject *other );
static int buffer_ass_slice ( PyBufferObject *self , int left , int right , PyObject *other );
static int buffer_getreadbuf ( PyBufferObject *self , int idx , void **pp );
static int buffer_getwritebuf ( PyBufferObject *self , int idx , void **pp );
static int buffer_getsegcount ( PyBufferObject *self , int *lenp );
static int buffer_getcharbuf ( PyBufferObject *self , int idx , const char **pp );
