static Py_complex c_powu ( Py_complex x , long n );
static Py_complex c_powi ( Py_complex x , long n );
static void complex_dealloc ( PyObject *op );
static void complex_buf_repr ( char *buf , PyComplexObject *v );
static int complex_print ( PyComplexObject *v , FILE *fp , int flags );
static PyObject *complex_repr ( PyComplexObject *v );
static int complex_compare ( PyComplexObject *v , PyComplexObject *w );
static long complex_hash ( PyComplexObject *v );
static PyObject *complex_add ( PyComplexObject *v , PyComplexObject *w );
static PyObject *complex_sub ( PyComplexObject *v , PyComplexObject *w );
static PyObject *complex_mul ( PyComplexObject *v , PyComplexObject *w );
static PyObject *complex_div ( PyComplexObject *v , PyComplexObject *w );
static PyObject *complex_remainder ( PyComplexObject *v , PyComplexObject *w );
static PyObject *complex_divmod ( PyComplexObject *v , PyComplexObject *w );
static PyObject *complex_pow ( PyComplexObject *v , PyObject *w , PyComplexObject *z );
static PyObject *complex_neg ( PyComplexObject *v );
static PyObject *complex_pos ( PyComplexObject *v );
static PyObject *complex_abs ( PyComplexObject *v );
static int complex_nonzero ( PyComplexObject *v );
static int complex_coerce ( PyObject **pv , PyObject **pw );
static PyObject *complex_int ( PyObject *v );
static PyObject *complex_long ( PyObject *v );
static PyObject *complex_float ( PyObject *v );
static PyObject *complex_conjugate ( PyObject *self , PyObject *args );
static PyObject *complex_getattr ( PyComplexObject *self , char *name );
