static dictentry *lookdict ( dictobject *mp , PyObject *key , long hash );
static void insertdict ( dictobject *mp , PyObject *key , long hash , PyObject *value );
static int dictresize ( dictobject *mp , int minused );
static void dict_dealloc ( dictobject *mp );
static int dict_print ( dictobject *mp , FILE *fp , int flags );
static PyObject *dict_repr ( dictobject *mp );
static int dict_length ( dictobject *mp );
static PyObject *dict_subscript ( dictobject *mp , PyObject *key );
static int dict_ass_sub ( dictobject *mp , PyObject *v , PyObject *w );
static PyObject *dict_keys ( dictobject *mp , PyObject *args );
static PyObject *dict_values ( dictobject *mp , PyObject *args );
static PyObject *dict_items ( dictobject *mp , PyObject *args );
static PyObject *dict_update ( dictobject *mp , PyObject *args );
static PyObject *dict_copy ( dictobject *mp , PyObject *args );
static PyObject *characterize ( dictobject *a , dictobject *b , PyObject **pval );
static int dict_compare ( dictobject *a , dictobject *b );
static int dict_compare ( dictobject *a , dictobject *b );
static PyObject *dict_has_key ( dictobject *mp , PyObject *args );
static PyObject *dict_get ( dictobject *mp , PyObject *args );
static PyObject *dict_clear ( dictobject *mp , PyObject *args );
static PyObject *dict_getattr ( dictobject *mp , char *name );
