static int roundupsize ( int n );
static int ins1 ( PyListObject *self , int where , PyObject *v );
static void list_dealloc ( PyListObject *op );
static int list_print ( PyListObject *op , FILE *fp , int flags );
static PyObject *list_repr ( PyListObject *v );
static int list_compare ( PyListObject *v , PyListObject *w );
static int list_length ( PyListObject *a );
static PyObject *list_item ( PyListObject *a , int i );
static PyObject *list_slice ( PyListObject *a , int ilow , int ihigh );
static PyObject *list_concat ( PyListObject *a , PyObject *bb );
static PyObject *list_repeat ( PyListObject *a , int n );
static int list_ass_slice ( PyListObject *a , int ilow , int ihigh , PyObject *v );
static int list_ass_item ( PyListObject *a , int i , PyObject *v );
static PyObject *ins ( PyListObject *self , int where , PyObject *v );
static PyObject *listinsert ( PyListObject *self , PyObject *args );
static PyObject *listappend ( PyListObject *self , PyObject *args );
static PyObject *listextend ( PyListObject *self , PyObject *args );
static PyObject *listpop ( PyListObject *self , PyObject *args );
static int docompare ( PyObject *x , PyObject *y , PyObject *compare );
static int binarysort ( PyObject **lo , PyObject **hi , PyObject **start , PyObject *compare );
static int samplesortslice ( PyObject **lo , PyObject **hi , PyObject *compare );
static PyObject *listsort ( PyListObject *self , PyObject *compare );
static PyObject *listreverse ( PyListObject *self , PyObject *args );
static PyObject *listindex ( PyListObject *self , PyObject *args );
static PyObject *listcount ( PyListObject *self , PyObject *args );
static PyObject *listremove ( PyListObject *self , PyObject *args );
static PyObject *list_getattr ( PyListObject *f , char *name );
static PyObject *immutable_list_op ( void );
static PyObject *immutable_list_getattr ( PyListObject *f , char *name );
static int immutable_list_ass ( void );
