static int long_divrem ( PyLongObject *a , PyLongObject *b , PyLongObject **pdiv , PyLongObject **prem );
static PyLongObject *x_divrem ( PyLongObject *v1 , PyLongObject *w1 , PyLongObject **prem );
static void long_dealloc ( PyObject *v );
static PyObject *long_repr ( PyObject *v );
static int long_compare ( PyLongObject *a , PyLongObject *b );
static long long_hash ( PyLongObject *v );
static PyLongObject *x_add ( PyLongObject *a , PyLongObject *b );
static PyLongObject *x_sub ( PyLongObject *a , PyLongObject *b );
static PyObject *long_add ( PyLongObject *a , PyLongObject *b );
static PyObject *long_sub ( PyLongObject *a , PyLongObject *b );
static PyObject *long_mul ( PyLongObject *a , PyLongObject *b );
static int l_divmod ( PyLongObject *v , PyLongObject *w , PyLongObject **pdiv , PyLongObject **pmod );
static PyObject *long_div ( PyLongObject *v , PyLongObject *w );
static PyObject *long_mod ( PyLongObject *v , PyLongObject *w );
static PyObject *long_divmod ( PyLongObject *v , PyLongObject *w );
static PyObject *long_pow ( PyLongObject *a , PyLongObject *b , PyLongObject *c );
static PyObject *long_invert ( PyLongObject *v );
static PyObject *long_pos ( PyLongObject *v );
static PyObject *long_neg ( PyLongObject *v );
static PyObject *long_abs ( PyLongObject *v );
static PyObject *long_str ( PyObject *v );
static int long_nonzero ( PyLongObject *v );
static PyObject *long_rshift ( PyLongObject *a , PyLongObject *b );
static PyObject *long_lshift ( PyLongObject *a , PyLongObject *b );
static PyObject *long_bitwise ( PyLongObject *a , int op , PyLongObject *b );
static PyObject *long_and ( PyLongObject *a , PyLongObject *b );
static PyObject *long_xor ( PyLongObject *a , PyLongObject *b );
static PyObject *long_or ( PyLongObject *a , PyLongObject *b );
static int long_coerce ( PyObject **pv , PyObject **pw );
static PyObject *long_int ( PyObject *v );
static PyObject *long_long ( PyObject *v );
static PyObject *long_float ( PyObject *v );
static PyObject *long_oct ( PyObject *v );
static PyObject *long_hex ( PyObject *v );
