static void range_dealloc ( rangeobject *r );
static PyObject *range_item ( rangeobject *r , int i );
static int range_length ( rangeobject *r );
static int range_print ( rangeobject *r , FILE *fp , int flags );
static PyObject *range_repr ( rangeobject *r );
static PyObject *range_concat ( rangeobject *r , PyObject *obj );
static PyObject *range_repeat ( rangeobject *r , int n );
static int range_compare ( rangeobject *r1 , rangeobject *r2 );
static PyObject *range_slice ( rangeobject *r , int low , int high );
static PyObject *range_tolist ( rangeobject *self , PyObject *args );
static PyObject *range_getattr ( rangeobject *r , char *name );
