static PyObject *c_getitem ( arrayobject *ap , int i );
static int c_setitem ( arrayobject *ap , int i , PyObject *v );
static PyObject *b_getitem ( arrayobject *ap , int i );
static int b_setitem ( arrayobject *ap , int i , PyObject *v );
static PyObject *BB_getitem ( arrayobject *ap , int i );
static PyObject *h_getitem ( arrayobject *ap , int i );
static int h_setitem ( arrayobject *ap , int i , PyObject *v );
static PyObject *HH_getitem ( arrayobject *ap , int i );
static PyObject *i_getitem ( arrayobject *ap , int i );
static int i_setitem ( arrayobject *ap , int i , PyObject *v );
static PyObject *II_getitem ( arrayobject *ap , int i );
static int II_setitem ( arrayobject *ap , int i , PyObject *v );
static PyObject *l_getitem ( arrayobject *ap , int i );
static int l_setitem ( arrayobject *ap , int i , PyObject *v );
static PyObject *LL_getitem ( arrayobject *ap , int i );
static int LL_setitem ( arrayobject *ap , int i , PyObject *v );
static PyObject *f_getitem ( arrayobject *ap , int i );
static int f_setitem ( arrayobject *ap , int i , PyObject *v );
static PyObject *d_getitem ( arrayobject *ap , int i );
static int d_setitem ( arrayobject *ap , int i , PyObject *v );
static PyObject *newarrayobject ( int size , struct arraydescr *descr );
static PyObject *getarrayitem ( PyObject *op , int i );
static int ins1 ( arrayobject *self , int where , PyObject *v );
static void array_dealloc ( arrayobject *op );
static int array_compare ( arrayobject *v , arrayobject *w );
static int array_length ( arrayobject *a );
static PyObject *array_item ( arrayobject *a , int i );
static PyObject *array_slice ( arrayobject *a , int ilow , int ihigh );
static PyObject *array_concat ( arrayobject *a , PyObject *bb );
static PyObject *array_repeat ( arrayobject *a , int n );
static int array_ass_slice ( arrayobject *a , int ilow , int ihigh , PyObject *v );
static int array_ass_item ( arrayobject *a , int i , PyObject *v );
static int setarrayitem ( PyObject *a , int i , PyObject *v );
static PyObject *ins ( arrayobject *self , int where , PyObject *v );
static PyObject *array_insert ( arrayobject *self , PyObject *args );
static PyObject *array_buffer_info ( arrayobject *self , PyObject *args );
static PyObject *array_append ( arrayobject *self , PyObject *args );
static PyObject *array_byteswap ( arrayobject *self , PyObject *args );
static PyObject *array_reverse ( arrayobject *self , PyObject *args );
static PyObject *array_fromfile ( arrayobject *self , PyObject *args );
static PyObject *array_tofile ( arrayobject *self , PyObject *args );
static PyObject *array_fromlist ( arrayobject *self , PyObject *args );
static PyObject *array_tolist ( arrayobject *self , PyObject *args );
static PyObject *array_fromstring ( arrayobject *self , PyObject *args );
static PyObject *array_tostring ( arrayobject *self , PyObject *args );
static PyObject *array_getattr ( arrayobject *a , char *name );
static int array_print ( arrayobject *a , FILE *fp , int flags );
static PyObject *array_repr ( arrayobject *a );
static int array_buffer_getreadbuf ( arrayobject *self , int index , const void **ptr );
static int array_buffer_getwritebuf ( arrayobject *self , int index , const void **ptr );
static int array_buffer_getsegcount ( arrayobject *self , int *lenp );
static PyObject *a_array ( PyObject *self , PyObject *args );
