static Py_complex c_acos ( Py_complex x );
static Py_complex c_acosh ( Py_complex x );
static Py_complex c_asin ( Py_complex x );
static Py_complex c_asinh ( Py_complex x );
static Py_complex c_atan ( Py_complex x );
static Py_complex c_atanh ( Py_complex x );
static Py_complex c_cos ( Py_complex x );
static Py_complex c_cosh ( Py_complex x );
static Py_complex c_exp ( Py_complex x );
static Py_complex c_log ( Py_complex x );
static Py_complex c_log10 ( Py_complex x );
static Py_complex c_prodi ( Py_complex x );
static Py_complex c_sin ( Py_complex x );
static Py_complex c_sinh ( Py_complex x );
static Py_complex c_sqrt ( Py_complex x );
static Py_complex c_tan ( Py_complex x );
static Py_complex c_tanh ( Py_complex x );
static PyObject *math_error ( void );
static PyObject *math_1 ( PyObject *args , Py_complex (*func )Py_FPROTO ((Py_complex )));
