static void set_seed ( Rotorobj *r );
static double r_random ( Rotorobj *r );
static short r_rand ( Rotorobj *r , int s );
static void set_key ( Rotorobj *r , char *key );
static Rotorobj *rotorobj_new ( int num_rotors , char *key );
static void RTR_make_id_rotor ( Rotorobj *r , unsigned char *rtr );
static void RTR_e_rotors ( Rotorobj *r );
static void RTR_d_rotors ( Rotorobj *r );
static void RTR_positions ( Rotorobj *r );
static void RTR_advances ( Rotorobj *r );
static void RTR_permute_rotor ( Rotorobj *r , unsigned char *e , unsigned char *d );
static void RTR_init ( Rotorobj *r );
static void RTR_advance ( Rotorobj *r );
static unsigned char RTR_e_char ( Rotorobj *r , unsigned char p );
static unsigned char RTR_d_char ( Rotorobj *r , unsigned char c );
static void RTR_e_region ( Rotorobj *r , unsigned char *beg , int len , int doinit );
static void RTR_d_region ( Rotorobj *r , unsigned char *beg , int len , int doinit );
static void rotor_dealloc ( Rotorobj *xp );
static PyObject *rotorobj_encrypt ( Rotorobj *self , PyObject *args );
static PyObject *rotorobj_encrypt_more ( Rotorobj *self , PyObject *args );
static PyObject *rotorobj_decrypt ( Rotorobj *self , PyObject *args );
static PyObject *rotorobj_decrypt_more ( Rotorobj *self , PyObject *args );
static PyObject *rotorobj_setkey ( Rotorobj *self , PyObject *args );
static PyObject *rotorobj_getattr ( Rotorobj *s , char *name );
static PyObject *rotor_rotor ( PyObject *self , PyObject *args );
