static PyObject *split_whitespace ( char *s , int len , int maxsplit );
static PyObject *strop_splitfields ( PyObject *self , PyObject *args );
static PyObject *strop_joinfields ( PyObject *self , PyObject *args );
static PyObject *strop_find ( PyObject *self , PyObject *args );
static PyObject *strop_rfind ( PyObject *self , PyObject *args );
static PyObject *do_strip ( PyObject *args , int striptype );
static PyObject *strop_strip ( PyObject *self , PyObject *args );
static PyObject *strop_lstrip ( PyObject *self , PyObject *args );
static PyObject *strop_rstrip ( PyObject *self , PyObject *args );
static PyObject *strop_lower ( PyObject *self , PyObject *args );
static PyObject *strop_upper ( PyObject *self , PyObject *args );
static PyObject *strop_capitalize ( PyObject *self , PyObject *args );
static PyObject *strop_expandtabs ( PyObject *self , PyObject *args );
static PyObject *strop_count ( PyObject *self , PyObject *args );
static PyObject *strop_swapcase ( PyObject *self , PyObject *args );
static PyObject *strop_atoi ( PyObject *self , PyObject *args );
static PyObject *strop_atol ( PyObject *self , PyObject *args );
static PyObject *strop_atof ( PyObject *self , PyObject *args );
static PyObject *strop_maketrans ( PyObject *self , PyObject *args );
static PyObject *strop_translate ( PyObject *self , PyObject *args );
static int mymemfind ( char *mem , int len , char *pat , int pat_len );
static int mymemcnt ( char *mem , int len , char *pat , int pat_len );
static char *mymemreplace ( char *str , int len , char *pat , int pat_len , char *sub , int sub_len , int count , int *out_len );
static PyObject *strop_replace ( PyObject *self , PyObject *args );
