static PyObject *nu_char ( const char *p , const formatdef *f );
static PyObject *nu_byte ( const char *p , const formatdef *f );
static PyObject *nu_ubyte ( const char *p , const formatdef *f );
static PyObject *nu_short ( const char *p , const formatdef *f );
static PyObject *nu_ushort ( const char *p , const formatdef *f );
static PyObject *nu_int ( const char *p , const formatdef *f );
static PyObject *nu_uint ( const char *p , const formatdef *f );
static PyObject *nu_long ( const char *p , const formatdef *f );
static PyObject *nu_ulong ( const char *p , const formatdef *f );
static PyObject *nu_float ( const char *p , const formatdef *f );
static PyObject *nu_double ( const char *p , const formatdef *f );
static PyObject *nu_void_p ( const char *p , const formatdef *f );
static int np_byte ( char *p , PyObject *v , const formatdef *f );
static int np_char ( char *p , PyObject *v , const formatdef *f );
static int np_short ( char *p , PyObject *v , const formatdef *f );
static int np_int ( char *p , PyObject *v , const formatdef *f );
static int np_uint ( char *p , PyObject *v , const formatdef *f );
static int np_long ( char *p , PyObject *v , const formatdef *f );
static int np_ulong ( char *p , PyObject *v , const formatdef *f );
static int np_float ( char *p , PyObject *v , const formatdef *f );
static int np_double ( char *p , PyObject *v , const formatdef *f );
static int np_void_p ( char *p , PyObject *v , const formatdef *f );
static PyObject *bu_int ( const char *p , const formatdef *f );
static PyObject *bu_uint ( const char *p , const formatdef *f );
static PyObject *bu_float ( const char *p , const formatdef *f );
static PyObject *bu_double ( const char *p , const formatdef *f );
static int bp_int ( char *p , PyObject *v , const formatdef *f );
static int bp_uint ( char *p , PyObject *v , const formatdef *f );
static int bp_float ( char *p , PyObject *v , const formatdef *f );
static int bp_double ( char *p , PyObject *v , const formatdef *f );
static PyObject *lu_int ( const char *p , const formatdef *f );
static PyObject *lu_uint ( const char *p , const formatdef *f );
static PyObject *lu_float ( const char *p , const formatdef *f );
static PyObject *lu_double ( const char *p , const formatdef *f );
static int lp_int ( char *p , PyObject *v , const formatdef *f );
static int lp_uint ( char *p , PyObject *v , const formatdef *f );
static int lp_float ( char *p , PyObject *v , const formatdef *f );
static int lp_double ( char *p , PyObject *v , const formatdef *f );
static const formatdef *whichtable ( const char **pfmt );
static const formatdef *getentry ( int c , const formatdef *f );
static int align ( int size , int c , const formatdef *e );
static int calcsize ( const char *fmt , const formatdef *f );
