static PyObject *builtin___import__ ( PyObject *self , PyObject *args );
static PyObject *builtin_abs ( PyObject *self , PyObject *args );
static PyObject *builtin_apply ( PyObject *self , PyObject *args );
static PyObject *builtin_buffer ( PyObject *self , PyObject *args );
static PyObject *builtin_callable ( PyObject *self , PyObject *args );
static PyObject *builtin_filter ( PyObject *self , PyObject *args );
static PyObject *builtin_chr ( PyObject *self , PyObject *args );
static PyObject *builtin_cmp ( PyObject *self , PyObject *args );
static PyObject *builtin_coerce ( PyObject *self , PyObject *args );
static PyObject *builtin_compile ( PyObject *self , PyObject *args );
static PyObject *complex_from_string ( PyObject *v );
static PyObject *builtin_complex ( PyObject *self , PyObject *args );
static PyObject *builtin_dir ( PyObject *self , PyObject *args );
static PyObject *builtin_divmod ( PyObject *self , PyObject *args );
static PyObject *builtin_eval ( PyObject *self , PyObject *args );
static PyObject *builtin_execfile ( PyObject *self , PyObject *args );
static PyObject *builtin_float ( PyObject *self , PyObject *args );
static PyObject *builtin_getattr ( PyObject *self , PyObject *args );
static PyObject *builtin_globals ( PyObject *self , PyObject *args );
static PyObject *builtin_hasattr ( PyObject *self , PyObject *args );
static PyObject *builtin_id ( PyObject *self , PyObject *args );
static PyObject *builtin_map ( PyObject *self , PyObject *args );
static PyObject *builtin_setattr ( PyObject *self , PyObject *args );
static PyObject *builtin_delattr ( PyObject *self , PyObject *args );
static PyObject *builtin_hash ( PyObject *self , PyObject *args );
static PyObject *builtin_hex ( PyObject *self , PyObject *args );
static PyObject *builtin_input ( PyObject *self , PyObject *args );
static PyObject *builtin_intern ( PyObject *self , PyObject *args );
static PyObject *builtin_int ( PyObject *self , PyObject *args );
static PyObject *builtin_len ( PyObject *self , PyObject *args );
static PyObject *builtin_list ( PyObject *self , PyObject *args );
static PyObject *builtin_slice ( PyObject *self , PyObject *args );
static PyObject *builtin_locals ( PyObject *self , PyObject *args );
static PyObject *builtin_long ( PyObject *self , PyObject *args );
static PyObject *min_max ( PyObject *args , int sign );
static PyObject *builtin_min ( PyObject *self , PyObject *v );
static PyObject *builtin_max ( PyObject *self , PyObject *v );
static PyObject *builtin_oct ( PyObject *self , PyObject *args );
static PyObject *builtin_open ( PyObject *self , PyObject *args );
static PyObject *builtin_ord ( PyObject *self , PyObject *args );
static PyObject *builtin_pow ( PyObject *self , PyObject *args );
static long get_len_of_range ( long lo , long hi , long step );
static PyObject *builtin_range ( PyObject *self , PyObject *args );
static PyObject *builtin_xrange ( PyObject *self , PyObject *args );
static PyObject *builtin_raw_input ( PyObject *self , PyObject *args );
static PyObject *builtin_reduce ( PyObject *self , PyObject *args );
static PyObject *builtin_reload ( PyObject *self , PyObject *args );
static PyObject *builtin_repr ( PyObject *self , PyObject *args );
static PyObject *builtin_round ( PyObject *self , PyObject *args );
static PyObject *builtin_str ( PyObject *self , PyObject *args );
static PyObject *builtin_tuple ( PyObject *self , PyObject *args );
static PyObject *builtin_type ( PyObject *self , PyObject *args );
static PyObject *builtin_vars ( PyObject *self , PyObject *args );
static PyObject *builtin_isinstance ( PyObject *self , PyObject *args );
static PyObject *builtin_issubclass ( PyObject *self , PyObject *args );
static int init_class_exc ( PyObject *dict );
static void fini_instances ( void );
static PyObject *newstdexception ( PyObject *dict , char *name );
static void initerrors ( PyObject *dict );
static void finierrors ( void );
static PyObject *filtertuple ( PyObject *func , PyObject *tuple );
static PyObject *filterstring ( PyObject *func , PyObject *strobj );
